### ISSUE TITLE
Add CI to build PDF

### ISSUE THREAD

**Issue by yungyuc** [solvcon/mmnote#5]
Github Actions workflow should be created to build the PDF on each push, PR, and nightly.

**Comment by tai271828** [comment]
I noticed the python module `modmesh` is required. Since we do not release any modmesh (please correct me if I am wrong), we may build `modmesh` from source in the CI, and the current build time on Github Action is ~10m. Given that, will we happy the ten-ish minutes of buildi time, or maybe we can prepare/release an early version of modmesh as a python package?

**Comment by yungyuc** [comment]
`modmesh` is not required for building the PDF.  Could you provide the error messages if there are errors associated with it when `make`?

**Comment by tai271828** [comment]
> `modmesh` is not required for building the PDF. Could you provide the error messages if there are errors associated with it when `make`?

Sure. Reproducing steps:

```
mmnote $ make
```

and I would get:

```
Having EPS files: turgon_eps/mesh_2d_tri.eps turgon_eps/crossse.eps turgon_eps/tube_move_right.eps turgon_eps/elm_tet.eps turgon_eps/elm_pym.eps turgon_eps/elm_ln.eps turgon_eps/tube_zones.eps turgon_eps/cce.eps turgon_eps/tube_at_rest.eps turgon_eps/elm_psm.eps turgon_eps/nonuni.eps turgon_eps/elm_quad.eps turgon_eps/elm_hex.eps turgon_eps/elm_tri.eps turgon_eps/mesh_2d_ce.eps turgon_eps/ctau.eps turgon_eps/cese_marching.eps turgon_eps/se_flux.eps turgon_eps/nonuni_se.eps
mkdir -p log ; num=1 ; while [ $num -le 3  ] ; do \
        latex_logfile=log/cese.dvi.latex.$num.log ; \
        echo -n "latex cese.dvi #$num ... " ; \
        latex -halt-on-error -interaction=nonstopmode -synctex=1 cese.tex 2>&1 | \
                tee $latex_logfile > /dev/null ; \
        if [[ \
                   ( -z "`grep 'LaTeX Error:' $latex_logfile`" ) \
                && ( -z "`grep 'Runaway argument\?' $latex_logfile`" ) \
                && ( -z "`grep \! $latex_logfile | head -c 1 | grep \!`" ) \
        ]] ; then \
                echo "done" ; \
        else \
                echo "tail $latex_logfile:" ; \
                tail $latex_logfile ; \
                exit -1 ; \
        fi ; \
        bibtex cese 2>&1 | \
                tee log/cese.dvi.bibtex.$num.log \
                > /dev/null ; \
(( num = num + 1 )) ; done
latex cese.dvi #1 ... tail log/cese.dvi.latex.1.log:

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.136   \includegraphics{cese_marching.eps}
                                           
Output written on cese.dvi (4 pages, 10444 bytes).
SyncTeX written on cese.synctex.gz.
Transcript written on cese.log.
make: *** [Makefile:94: cese.dvi] Error 255
rm cese.dvi
```

and then I dived into `cese.log`, it shows:

```
! LaTeX Error: File `cese_marching.eps' not found.
```

besides, `./log/cese_marching.py.log` shows:

```
Traceback (most recent call last):                                                                                                                                                                                                           
  File "schematic/cese_marching.py", line 4, in <module>
    import modmesh as mm
ModuleNotFoundError: No module named 'modmesh'
```

Let me paste both `cese.log` and `./log/cese_marching.py.log`.

**Comment by tai271828** [comment]
[cese.log](https://github.com/solvcon/mmnote/files/9841952/cese.log)
[cese_marching.py.log](https://github.com/solvcon/mmnote/files/9841953/cese_marching.py.log)

**Comment by yungyuc** [comment]
There seems to be something wrong with your local repository.  It is not necessary to run `cese_marching.py`, because `cese_marching.tex` is already there: https://github.com/solvcon/mmnote/blob/master/schematic/cese_marching.tex .  Could you look into it?

**Comment by tai271828** [comment]
Sure. Will do!

**Comment by tai271828** [comment]
Ah, `make clean` removes the following files:

```
[^_^]─[~/work-my-projects/solvcon/mmnote] tai271828@syakaro: 221027-23:57:39 40 file 1.1Mb
$ make clean
rm -f *.aux *.bbl *.blg *.dvi *.log *.out *.xwm *.toc *.pdf *.ps \
        *.fdb_latexmk *.fls *.pdfsync *.synctex.gz
rm -rf log
rm -rf turgon_eps
rm -f schematic/cese_marching.tex schematic/se_flux.tex schematic/nonuni_se.tex
[^_^]─[~/work-my-projects/solvcon/mmnote] tai271828@syakaro: 221027-23:57:41 12 file 200Kb
$ git status
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        deleted:    schematic/cese_marching.tex
        deleted:    schematic/nonuni_se.tex
        deleted:    schematic/se_flux.tex

no changes added to commit (use "git add" and/or "git commit -a")
```

**Comment by yungyuc** [comment]
> Ah, `make clean` removes the following files:

Oops, it's a bug.  #17 is created to track it.

**Comment by tai271828** [comment]
Random thoughts: We can not only provide the artifacts[1], but also a badge in the README of project page.

[1] https://github.com/solvcon/mmnote/pull/16#issuecomment-1294241441

**Comment by yungyuc** [comment]
A badge sounds like cool indeed.

**Comment by yungyuc** [comment]
@EN-Chou would you please take a look at making the github actions to produce the artifacts: https://docs.github.com/en/actions/using-workflows/storing-workflow-data-as-artifacts ?

**Comment by tai271828** [comment]
I am in a business trip for the coming two weeks, and I won't be available to work on this issue. If anyone is interested in working on this issue, feel free to ping me or ask me questions. I am happy to help.

**Comment by EN-Chou** [comment]
@yungyuc @tai271828 Are those cleaned up by `make clean` artifacts? If they are, how are they related to github actions?

**Comment by yungyuc** [comment]
`make clean` has nothing to do with github actions artifacts.  Does that answer your question?
