### ISSUE TITLE
Create hook to discord

### ISSUE THREAD

**Issue by yungyuc** [solvcon/mmnote#8]
After CI automation is created (#5), we should hook the repository to discord #solvcon-notif

**Comment by yungyuc** [comment]
@tai271828 Could you also help this?

**Comment by tai271828** [comment]
I added a webhook of github. See the posted message to discord #solvcon-notif https://discord.com/channels/730297880140578906/766221728652853248/1057258344848572446

**Comment by tai271828** [comment]
Let me know if this hook meets the team's expectation. If yes, let's close this issue, or let me tweak the hook until it meets the expectation of the team.

**Comment by yungyuc** [comment]
It works perfectly.  Thanks a lot
